/* Attended user-gesture injection. No credentials, OTP guessing or CAPTCHA bypass. */
(()=>{if(window.__internshipOS)return;
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
const visible=e=>!!(e.getClientRects().length)&&getComputedStyle(e).visibility!=='hidden';
const label=e=>[...Array.from(e.labels||[]).map(l=>l.textContent),e.getAttribute('aria-label'),e.getAttribute('placeholder'),e.name,e.id,e.getAttribute('autocomplete')].filter(Boolean).join(' ').trim();
const provider=()=>{const h=location.hostname;return h.endsWith('.greenhouse.io')?'greenhouse':h.endsWith('.lever.co')?'lever':h.endsWith('.ashbyhq.com')?'ashby':null;};
function receipt(){for(const e of document.querySelectorAll('h1,h2,[role="alert"],[data-testid*="success"],.application-confirmation')){const text=e.textContent.trim();if(visible(e)&&/application (received|submitted)|thank you for applying|thanks for applying|successfully submitted/i.test(text))return {url:location.href,evidence:text.slice(0,1500)};}return null;}
function capture(){let job=null;for(const script of document.querySelectorAll('script[type="application/ld+json"]')){try{const data=JSON.parse(script.textContent);const stack=[data];while(stack.length){const x=stack.pop();if(Array.isArray(x)){stack.push(...x);continue;}if(x&&typeof x==='object'){if([x['@type']].flat().includes('JobPosting')){job=x;break;}if(x['@graph'])stack.push(x['@graph']);}}}catch{}if(job)break;}
const container=document.createElement('div');container.innerHTML=job?.description||'';const loc=job?.jobLocation;return {url:location.href,title:job?.title||document.querySelector('h1')?.textContent?.trim()||document.title,company_name:job?.hiringOrganization?.name||document.querySelector('[data-company-name]')?.getAttribute('data-company-name')||'',company_domain:job?.hiringOrganization?.sameAs?new URL(job.hiringOrganization.sameAs).hostname:undefined,location:loc?.address?.addressLocality||'',description:job?container.textContent:(document.querySelector('main,article,[role="main"]')||document.body).innerText.slice(0,70000),apply_url:location.href};}
function resolve(e,args){const l=norm(label(e)),f=args.localFacts||{},p=args.pack.fields||{},a=f.answers||{};const exact=Object.keys(a).find(q=>norm(q)===norm(Array.from(e.labels||[]).map(x=>x.textContent).join(' ')||e.getAttribute('aria-label')||label(e)));if(exact)return String(a[exact]);if(/authorization|authorisation|sponsor|citizenship|legally|demographic|gender|race|ethnicity|disability|veteran|salary|compensation|consent|agree|terms|criminal|relocat/.test(l))return undefined;const name=f.fullName||p.name||p.display_name||'';if(/first name|given name|given-name/.test(l))return name.split(' ')[0];if(/last name|family name|surname/.test(l))return name.split(' ').slice(1).join(' ');if(/full name|your name|^name$/.test(l))return name;if(/email/.test(l))return f.email||p.email;if(/phone|mobile/.test(l))return f.phone||p.phone;if(/linkedin/.test(l))return f.linkedin||p.linkedin_url;if(/github/.test(l))return f.github||p.github_url;if(/university|school name|college name/.test(l))return p.university;return undefined;}
function setValue(e,value){if(e.tagName==='SELECT'){const options=Array.from(e.options);const option=options.find(o=>norm(o.textContent)===norm(value)||norm(o.value)===norm(value));if(!option)return false;e.value=option.value;}else{const prototype=e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(prototype,'value')?.set?.call(e,value);}e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));return true;}
async function fill(args){const filled=[],unresolved=[];let requiredFileMissing=false,resumeUploaded=false,resumeRequested=false;
for(const e of document.querySelectorAll('input,textarea,select')){if(!visible(e)||e.disabled||e.readOnly||['hidden','submit','button','password'].includes(e.type))continue;const l=label(e)||e.type;
if(e.type==='file'){if(/resume|cv/i.test(l))resumeRequested=true;if(args.file&&/resume|cv/i.test(l)){const bytes=Uint8Array.from(atob(args.file.base64),c=>c.charCodeAt(0));const transfer=new DataTransfer();transfer.items.add(new File([bytes],args.file.name,{type:'application/pdf'}));e.files=transfer.files;e.dispatchEvent(new Event('change',{bubbles:true}));filled.push(l);resumeUploaded=true;}else if(e.required&&!e.files?.length){unresolved.push(l);requiredFileMissing=true;}continue;}
if(['radio','checkbox'].includes(e.type)){const answer=resolve(e,args);if(answer!==undefined&&norm(e.value)===norm(answer)){e.checked=true;e.dispatchEvent(new Event('change',{bubbles:true}));filled.push(l);}continue;}
if(e.value&&String(e.value).trim())continue;const answer=resolve(e,args);if(answer!==undefined&&answer!==''&&setValue(e,String(answer)))filled.push(l);else if(e.required||e.getAttribute('aria-required')==='true')unresolved.push(l);}
await new Promise(r=>setTimeout(r,450));
for(const e of document.querySelectorAll('[required],[aria-required="true"]')){if(!visible(e)||e.disabled)continue;const empty=e.type==='checkbox'?!e.checked:e.type==='radio'?!document.querySelector(`input[type="radio"][name="${CSS.escape(e.name)}"]:checked`):e.type==='file'?!e.files?.length:e.tagName==='BUTTON'?!e.getAttribute('data-value'):!String(e.value||e.getAttribute('data-value')||'').trim();if(empty&&!unresolved.includes(label(e)))unresolved.push(label(e)||'Required question');}
const captcha=Array.from(document.querySelectorAll('iframe[src*="recaptcha"],iframe[src*="hcaptcha"],[data-sitekey]')).some(visible);const permitted=args.pack.auto_apply?.enabled&&args.pack.auto_apply.providers?.includes(provider());let submitted=false,message='Review required and sensitive answers before submission.';
let sameJob=false;try{const expected=new URL(args.pack.opportunity.apply_url||args.pack.opportunity.canonical_url);const path=expected.pathname.replace(/\/$/,'');sameJob=expected.hostname===location.hostname&&path.length>8&&(location.pathname===path||location.pathname.startsWith(path+'/'));if(expected.searchParams.get('gh_jid'))sameJob=expected.hostname===location.hostname&&new URL(location.href).searchParams.get('gh_jid')===expected.searchParams.get('gh_jid');}catch{}
if(args.submitConsent&&permitted){if(!sameJob)message='This page cannot be matched exactly to the selected job. Automatic submission stopped.';else if(captcha)message='CAPTCHA requires your attention. Automatic submission stopped.';else if(unresolved.length||requiredFileMissing)message='Required answers are missing or ambiguous. Automatic submission stopped.';else if(!args.pack.resume_version||args.pack.resume_version.status!=='approved')message='Select an approved resume version before automatic submission.';else if(resumeRequested&&!resumeUploaded)message='The selected resume was not attached successfully. Automatic submission stopped.';else if(!filled.length)message='No supported facts were filled. Review this form manually.';else{const button=Array.from(document.querySelectorAll('button[type="submit"],input[type="submit"]')).find(b=>visible(b)&&!b.disabled&&/submit|apply|send application/i.test(b.textContent||b.value));if(button){const form=button.closest('form');if(form&&form.reportValidity()){button.click();submitted=true;message='Submission attempted. A confirmation receipt is required.';}}else message='This submit control is not supported; finish manually.';}}
else if(args.submitConsent)message='Automatic submission is not authorized for this provider in workspace Settings.';
let found=receipt();if(submitted&&!found){for(let i=0;i<20&&!found;i++){await new Promise(r=>setTimeout(r,500));found=receipt();}}
return {filled,unresolved,message,submitted,receipt:found,resume_uploaded:resumeUploaded};}
window.__internshipOS={perform:(action,args)=>action==='capture'?capture():action==='receipt'?receipt():action==='fill'?fill(args):null,norm,provider};})();
