const $=id=>document.getElementById(id);
let connection={},pageInfo={},lastPack=null;
function status(text){$('status').textContent=text;}
async function request(path,method='GET',body){if(!connection.token)throw Error('Connect a pairing token from your workspace Settings.');const r=await fetch(connection.apiUrl.replace(/\/$/,'')+path,{method,headers:{Authorization:'Bearer '+connection.token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.detail||'Workspace request failed.');return data;}
async function activeTab(){const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id||!/^https?:/.test(tab.url||''))throw Error('Open a public career or application page first.');return tab;}
async function inject(action,args){const tab=await activeTab();await chrome.scripting.executeScript({target:{tabId:tab.id},files:['content.js']});const [result]=await chrome.scripting.executeScript({target:{tabId:tab.id},func:(action,args)=>window.__internshipOS.perform(action,args),args:[action,args]});return result.result;}
async function run(fn){try{status('WorkingÃ¢â‚¬Â¦');await fn();}catch(e){status(e.message);}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('section').forEach(s=>s.hidden=s.id!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));});
$('readPage').onclick=()=>run(async()=>{pageInfo=await inject('capture',{});$('jobTitle').value=pageInfo.title||'';$('company').value=pageInfo.company_name||'';$('location').value=pageInfo.location||'';status('Page read. Review the title and employer before saving.');});
$('savePage').onclick=()=>run(async()=>{if(!pageInfo.url)pageInfo=await inject('capture',{});await request('/capture','POST',{...pageInfo,title:$('jobTitle').value,company_name:$('company').value,location:$('location').value});status('Saved with the original page as evidence.');});
$('connect').onclick=()=>run(async()=>{const url=new URL($('apiUrl').value);if(url.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(url.hostname))throw Error('Use HTTPS for a hosted workspace.');await chrome.permissions.request({origins:[url.origin+'/*']});connection={apiUrl:$('apiUrl').value,token:$('token').value};await request('/extension/applications');await chrome.storage.local.set({connection});status('Workspace connected.');});
$('saveFacts').onclick=()=>run(async()=>{const answers=$('answers').value.trim()?JSON.parse($('answers').value):{};if(Array.isArray(answers)||typeof answers!=='object')throw Error('Question answers must be a JSON object.');await chrome.storage.local.set({facts:{fullName:$('fullName').value,email:$('email').value,phone:$('phone').value,linkedin:$('linkedin').value,github:$('github').value,answers}});status('Facts saved locally in this browser.');});
$('loadApplications').onclick=()=>run(async()=>{const data=await request('/extension/applications');$('application').replaceChildren(new Option('Select an application',''));data.items.forEach(a=>$('application').append(new Option(a.company+' Ã‚Â· '+a.title+' ('+a.stage+')',a.id)));status('Applications refreshed.');});
async function recordReceipt(receipt){if(!lastPack){const {activeApplicationId}=await chrome.storage.local.get('activeApplicationId');if(activeApplicationId)lastPack=await request('/extension/pack?application_id='+encodeURIComponent(activeApplicationId));}if(!lastPack)throw Error('Load an application pack first.');const {activeResumeVersionId}=await chrome.storage.local.get('activeResumeVersionId');await request('/extension/receipt','POST',{application_id:lastPack.application.id,resume_version_id:activeResumeVersionId||null,url:receipt.url,evidence:receipt.evidence});status('Confirmed receipt saved. The exact resume version is recorded.');}
$('fill').onclick=()=>run(async()=>{const id=$('application').value;if(!id)throw Error('Select an application first.');lastPack=await request('/extension/pack?application_id='+encodeURIComponent(id));await chrome.storage.local.set({activeApplicationId:id});const {facts={}}=await chrome.storage.local.get('facts');let file=null;if(lastPack.resume_download_url){const r=await fetch(new URL(lastPack.resume_download_url,new URL(connection.apiUrl).origin),{headers:{Authorization:'Bearer '+connection.token}});if(r.ok){const bytes=new Uint8Array(await r.arrayBuffer());file={base64:btoa(Array.from(bytes,b=>String.fromCharCode(b)).join('')),name:'resume-'+lastPack.resume_version.id.slice(0,8)+'.pdf'};}}
const result=await inject('fill',{pack:lastPack,localFacts:facts,file,submitConsent:$('submitConsent').checked});await chrome.storage.local.set({activeResumeVersionId:result.resume_uploaded?lastPack.resume_version.id:null});$('fieldReport').textContent=`Filled ${result.filled.length} fields.\n${result.unresolved.length?'Needs review: '+result.unresolved.join(', '):'No unresolved required fields detected.'}\n${result.message||''}`;if(result.receipt)await recordReceipt(result.receipt);else status(result.submitted?'Submission attempted; verify and check the receipt before recording it.':'Prepared. Review your form before submitting.');});
$('receipt').onclick=()=>run(async()=>{const receipt=await inject('receipt',{});if(!receipt)throw Error('No supported confirmation receipt is visible. Filling a form is not a submission.');await recordReceipt(receipt);});
chrome.storage.local.get(['connection','facts']).then(({connection:c,facts={}})=>{connection=c||{};$('apiUrl').value=connection.apiUrl||'http://127.0.0.1:8000/api';$('token').value=connection.token||'';for(const [id,key]of [['fullName','fullName'],['email','email'],['phone','phone'],['linkedin','linkedin'],['github','github']])$(id).value=facts[key]||'';$('answers').value=Object.keys(facts.answers||{}).length?JSON.stringify(facts.answers,null,2):'';if(connection.token)status('Connected. Your sensitive answers stay in this browser.');});
