import {useState} from 'react';
import {items,useResource,type Row} from './api';
import {Panel,Button,Badge,Field,useUI} from './ui';

export function ApplicationQueue(){
 const {data,refresh}=useResource('/application-queue');const {run}=useUI();const [reviewed,setReviewed]=useState<Record<string,boolean>>({});
 const rows=items(data).filter((a:Row)=>a.stage==='ready'||['in_progress','uncertain'].includes(a.state));
 return <Panel title="Approved application queue"><p className="muted">The browser extension executes approved packs. Automatic submission stays off until enabled in Settings. Changed jobs, answers or resume selections need review again.</p>{!rows.length?<p>No ready applications. Prepare a role and select an approved resume first.</p>:rows.map((a:Row)=><div className="source-evidence" key={a.id}><div><strong>{a.company} · {a.title}</strong><Badge>{a.state.replaceAll('_',' ')}</Badge>{a.blockers?.length>0&&<p className="small muted">{a.blockers.join(' ')}</p>}{a.state==='needs_review'||a.state==='revoked'?<><Field label="I reviewed this job's eligibility and application pack"><input type="checkbox" checked={!!reviewed[a.id]} onChange={e=>setReviewed({...reviewed,[a.id]:e.target.checked})}/></Field><Button disabled={!reviewed[a.id]} onClick={async()=>{await run(`/application-queue/${a.id}/approve`,'POST',{confirm:true,eligibility_reviewed:true},'Pack approved. Submission remains controlled by your extension.');refresh();}}>Approve this pack</Button></>:a.state==='approved'?<Button onClick={async()=>{await run(`/application-queue/${a.id}/revoke`,'POST',{},'Approval revoked');refresh();}}>Revoke approval</Button>:<p className="small">Check the employer confirmation before any further attempt. The queue will not retry automatically.</p>}</div></div>)}</Panel>;
}


export function CompanyPriorityEditor({company}:{company:Row}){
 const {run}=useUI();const [score,setScore]=useState(company.metadata_json?.company_priority?.score??30),[reason,setReason]=useState('');
 return <Panel title="Your company priority"><p>{company.metadata_json?.company_priority?.reason||'No preference recorded.'}</p><Field label="Priority (0 to 100)"><input type="number" min="0" max="100" value={score} onChange={e=>setScore(Number(e.target.value))}/></Field><Field label="Why this company matters to you"><input value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={reason.trim().length<8} onClick={()=>run(`/companies/${company.id}`,'PATCH',{company_priority:score,priority_reason:reason},'Company preference saved')}>Save company priority</Button></Panel>;
}

export function SourceAssociationReview({company}:{company:Row}){
 const {run}=useUI();const [source,setSource]=useState(''),[url,setUrl]=useState(''),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false);
 return <Panel title="Review a board association"><p className="muted">Confirm that this employer's official website links to the selected board. Company priority and a reachable board alone do not prove the association.</p><Field label="Source"><select value={source} onChange={e=>setSource(e.target.value)}><option value="">Choose a board</option>{items(company.sources).map(s=><option key={s.id} value={s.id}>{s.provider} · {s.url} {s.verified?'(verified)':''}</option>)}</select></Field><Field label="Official employer page linking to this board"><input type="url" value={url} onChange={e=>setUrl(e.target.value)}/></Field><Field label="Evidence you checked"><input value={reason} onChange={e=>setReason(e.target.value)}/></Field><label className="check-label"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I checked the official link and the employer identity.</label><Button disabled={!company.verified||!source||!url||reason.trim().length<8||!confirmed} onClick={()=>run(`/sources/${source}`,'PATCH',{verified:true,verification_url:url,verification_reason:reason},'Board association review saved')}>Verify this association</Button><Button disabled={!source} onClick={()=>run(`/sources/${source}`,'PATCH',{verified:false},'Board association verification revoked')}>Revoke verification</Button></Panel>;
}
