import { createContext, useContext, useEffect, useRef, useState } from 'react';
import type { ReactNode, FormEvent } from 'react';
import { ArrowUpRight, Check, ChevronRight, CircleHelp, Inbox, LoaderCircle, RefreshCw, Search, ShieldCheck, Sparkles, X } from 'lucide-react';
import { api, invalidate, numeric, readable, type Row } from './api';

type UIContextType={toast:(message:string,type?:'success'|'error')=>void;openOpportunity:(id:string)=>void;navigate:(page:string,query?:string)=>void;run:<T=Row>(path:string,method?:string,body?:unknown,message?:string)=>Promise<T|null>};
export const UIContext=createContext<UIContextType>({toast:()=>{},openOpportunity:()=>{},navigate:()=>{},run:async()=>null});
export const useUI=()=>useContext(UIContext);
export function Button({children,variant='secondary',className='',busy=false,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'|'danger';busy?:boolean}) { return <button {...props} disabled={props.disabled||busy} className={`button ${variant} ${className}`}>{busy?<LoaderCircle size={15} className="spin"/>:null}{children}</button>; }
export function Badge({children,tone='neutral',dot=false}:{children:ReactNode;tone?:string;dot?:boolean}) {return <span className={`badge ${tone}`}>{dot&&<i/>}{children}</span>;}
export function Score({value,label='Fit',confidence}:{value?:number|null;label?:string;confidence?:any}) {const n=numeric(value);return <span className={`score ${n!=null&&n>=70?'good':n!=null&&n<40?'low':''}`} title={`${label}: ${n??'not evaluated'}${confidence?` · ${readable(confidence)} confidence`:''}`}><span>{n==null?'—':Math.round(n)}</span><small>{label}</small></span>;}
export function CompanyMark({company,size='normal'}:{company?:Row;size?:string}) {return <div className={`company-mark ${size}`} aria-hidden="true">{(company?.name||'?').split(/\s/).slice(0,2).map((w:string)=>w[0]).join('').toUpperCase()}</div>;}
export function Empty({icon:Icon=Inbox,title,description,action}:{icon?:any;title:string;description?:string;action?:ReactNode}) {return <div className="empty"><div className="empty-icon"><Icon size={25} strokeWidth={1.4}/></div><h3>{title}</h3>{description&&<p>{description}</p>}{action}</div>;}
export function Skeleton({rows=4}:{rows?:number}) {return <div className="skeleton-group" aria-label="Loading" aria-busy="true">{Array.from({length:rows},(_,i)=><div className="skeleton-row" key={i}><div className="skeleton-avatar"/><div><div className="skeleton-line"/><div className="skeleton-line short"/></div></div>)}</div>;}
export function ErrorPanel({error,retry}:{error:string;retry?:()=>void}) {return <div className="error-panel" role="alert"><CircleHelp size={20}/><div><strong>Something needs attention</strong><p>{error}</p></div>{retry&&<Button onClick={retry}><RefreshCw size={14}/>Try again</Button>}</div>;}
export function Panel({title,subtitle,action,children,className=''}:{title?:string;subtitle?:string;action?:ReactNode;children:ReactNode;className?:string}) {return <section className={`panel ${className}`}>{(title||action)&&<div className="panel-header"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}{children}</section>;}
export function PageHeader({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description?:string;actions?:ReactNode}) {return <header className="page-header"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{actions&&<div className="page-actions">{actions}</div>}</header>;}
export function Field({label,hint,children,className=''}:{label:string;hint?:string;children:ReactNode;className?:string}) {return <label className={`field ${className}`}><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function SearchBox({value,onChange,placeholder='Search…'}:{value:string;onChange:(v:string)=>void;placeholder?:string}) {return <div className="search-field"><Search size={16}/><input aria-label={placeholder} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>{value&&<button aria-label="Clear search" onClick={()=>onChange('')}><X size={14}/></button>}</div>;}
export function Modal({title,subtitle,children,onClose,wide=false}:{title:string;subtitle?:string;children:ReactNode;onClose:()=>void;wide?:boolean}) {
  const ref=useRef<HTMLDivElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement; const bodyOverflow=document.body.style.overflow;document.body.style.overflow='hidden';const timer=setTimeout(()=>ref.current?.querySelector<HTMLElement>('button,input,select,textarea,[tabindex="0"]')?.focus(),0);const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'&&ref.current){const all=Array.from(ref.current.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,select,textarea,[tabindex="0"]')).filter(x=>x.offsetParent!==null);const first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{clearTimeout(timer);document.body.style.overflow=bodyOverflow;document.removeEventListener('keydown',key);previous?.focus();};},[onClose]);
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div ref={ref} className={`modal ${wide?'wide':''}`} role="dialog" aria-modal="true" aria-label={title}><div className="modal-header"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div><div className="modal-body">{children}</div></div></div>;
}
export function ProgressBar({value,max=100,tone='blue'}:{value:number;max?:number;tone?:string}) {return <div className={`progress-bar ${tone}`}><span style={{width:`${Math.max(0,Math.min(100,max?value/max*100:0))}%`}}/></div>;}
export function TextList({value,empty='No details available.'}:{value:any;empty?:string}) {const arr=Array.isArray(value)?value:typeof value==='string'?value.split('\n').filter(Boolean):[];return arr.length?<ul className="text-list">{arr.map((v:any,i:number)=><li key={i}>{typeof v==='object'?v.text||v.label||v.reason||v.evidence||JSON.stringify(v):v}</li>)}</ul>:<p className="muted">{empty}</p>;}
export function Stats({items}:{items:{label:string;value:ReactNode;note?:string;icon?:any;tone?:string;onClick?:()=>void}[]}) {return <div className="stats-grid">{items.map(({label,value,note,icon:Icon,tone,onClick})=><button className={`stat-card ${tone||''}`} key={label} onClick={onClick} disabled={!onClick}><div className="stat-top"><span>{label}</span>{Icon&&<Icon size={17}/>}</div><strong>{value??'—'}</strong><small>{note||' '}</small></button>)}</div>;}
export function Tabs({value,onChange,items}:{value:string;onChange:(v:string)=>void;items:{id:string;label:string;count?:number}[]}) {return <div className="tabs" role="tablist">{items.map(x=><button role="tab" aria-selected={value===x.id} className={value===x.id?'active':''} key={x.id} onClick={()=>onChange(x.id)}>{x.label}{x.count!=null&&<span>{x.count}</span>}</button>)}</div>;}
export function FormActions({busy,onClose,label='Save changes'}:{busy?:boolean;onClose?:()=>void;label?:string}) {return <div className="form-actions">{onClose&&<Button type="button" onClick={onClose}>Cancel</Button>}<Button variant="primary" busy={busy} type="submit"><Check size={15}/>{label}</Button></div>;}
export function useFormSubmit(action:(e:FormEvent)=>Promise<void>) {const [busy,setBusy]=useState(false);return {busy,submit:async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{await action(e);}finally{setBusy(false);}}};}
export const stageLabels:Record<string,string>={ready:'Ready to apply',applied:'Applied',oa:'Assessment',interview:'Interview',offer:'Offer',rejected:'Closed / rejected'};
export const trustTone=(v:string)=>v?.toLowerCase()==='verified'?'green':['high risk','high_risk'].includes(v?.toLowerCase())?'red':['needs review','needs_review'].includes(v?.toLowerCase())?'amber':'neutral';
